# Coright (c) 2024 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build hictk Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-hictk*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hictk*.Dockerfile"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-hictk*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hictk*.Dockerfile"

jobs:
  build-hictk-dockerfile:
    name: Build hictk Dockerfile
    uses: robomics/chrom3d-nf/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/hictk*.Dockerfile"

    permissions:
      contents: read
      packages: write
