# Copyright (c) 2024 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build Python utils Dockerfile

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-py-utils*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/py-utils*.Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build-py-utils*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/py-utils*.Dockerfile"

jobs:
  build-py-utils-dockerfile:
    name: Build Python utils Dockerfile
    uses: robomics/chrom3d-nf/.github/workflows/build-dockerfile.yml@daa0016a57f2dc25247d5fbf306025f91b32a1d7
    with:
      dockerfile-glob: "containers/py-utils*.Dockerfile"

    permissions:
      contents: read
      packages: write
