# Coright (c) 2024 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build hictk Dockerfile

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-hictk-dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hictk_*.Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build-hictk-dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hictk_*.Dockerfile"

jobs:
  build-hictk-dockerfile:
    name: Build hictk Dockerfile
    uses: robomics/chrom3d-nf/.github/workflows/build-dockerfile.yml@d78a0f312fc7272147f7edfb9245b1bf1f798e69
    with:
      dockerfile-glob: "containers/hictk_*.Dockerfile"

    permissions:
      contents: read
      packages: write
